### ISSUE TITLE
After the merge request #4, app loading failing 

### ISSUE THREAD

**Issue by Ks-Weasley** [SKS2024SE/Track-Ur-Tab#5]
![image](https://github.com/user-attachments/assets/200aff12-1f6c-412f-83bf-ffbd3a20bdd5)

Please find the attached image above. The personal expenses are not loading. Seems like a part of my code(PersonalExpenses.js) has been commented. @SandhiyaS24 Is there a particular reason why this change has been made?

**Comment by SandhiyaS24** [comment]
There has been some overlap between the files we have been working on. Somewhere the module import has been commented out.

**Comment by Sanjaeyss** [comment]
Shouldn't the git result in a conflict if such a scenario occurs?

**Comment by Ks-Weasley** [comment]
The git did not result in a conflict because the changes were present in different lines and a previous merge changed the owner of the lines. Hence, there was no conflict in these parts. I have pushed the fix for the file that got overlapped. 
@SandhiyaS24 @Sanjaeyss . Hence, the issue can be closed.
